#!/usr/bin/env python3
"""Regenerate the Design Contract token tables from the Compose theme source.

Parses the dark `IntelliJColors` palette and the `Spacing`/`Dimensions` objects in
`IntelliJColors.kt` and writes Markdown tables to `DESIGN_TOKENS.generated.md`.

Run from the repo root:  python3 tools/export_design_tokens.py

Keeping the contract tables generated (rather than hand-maintained) stops them drifting
from the code — re-run after changing the theme.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
THEME = REPO / "app/desktop/src/jvmMain/kotlin/su/kidoz/jetaprog/app/ui/theme/IntelliJColors.kt"
OUT = REPO / "DESIGN_TOKENS.generated.md"

COLOR_RE = re.compile(r"public val (\w+): Color = Color\(0x([0-9A-Fa-f]{8})\)")
INT_RE = re.compile(r"public val (\w+): Int = (\d+)")


def block(text: str, start_marker: str) -> str:
    """Return the body of the first object/block beginning at `start_marker`."""
    start = text.index(start_marker)
    depth, i = 0, text.index("{", start)
    body_start = i + 1
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[body_start:i]
        i += 1
    return text[body_start:]


def to_hex(argb: str) -> str:
    """0xAARRGGBB -> #RRGGBB (drop the alpha)."""
    return "#" + argb[2:].upper()


def main() -> None:
    src = THEME.read_text(encoding="utf-8")
    dark = block(src, "object IntelliJColors")
    colors = [(m.group(1), to_hex(m.group(2))) for m in COLOR_RE.finditer(dark)]
    spacing = INT_RE.findall(block(src, "object Spacing"))
    dimensions = INT_RE.findall(block(src, "object Dimensions"))

    lines = [
        "# Design Tokens (generated)",
        "",
        "> Generated by `tools/export_design_tokens.py` from `IntelliJColors.kt`. Do not edit by hand.",
        "",
        f"## Colors — dark palette ({len(colors)} literal tokens)",
        "",
        "| Token | Hex |",
        "|-------|-----|",
    ]
    lines += [f"| `{name}` | `{hex_}` |" for name, hex_ in colors]
    lines += ["", "## Spacing (dp)", "", "| Token | dp |", "|-------|----|"]
    lines += [f"| `{name}` | {val} |" for name, val in spacing]
    lines += ["", "## Dimensions (dp)", "", "| Token | dp |", "|-------|----|"]
    lines += [f"| `{name}` | {val} |" for name, val in dimensions]
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)}: {len(colors)} colors, "
          f"{len(spacing)} spacing, {len(dimensions)} dimensions.")


if __name__ == "__main__":
    main()
